default_platform(:ios)

$user_name = 'アプリ名 #漢字'
$workspace_name = 'ワークスペース名 #英語'
$env_name = '開発環境 #英語'
$scheme_name = 'スキーム名 #英語'
$ipa_name = 'アプリファイル #英語'
$success_message = '通知メッセージ #日本語'

build_time = Time.new.strftime("%m/%d")
full_time = Time.new.strftime("%Y/%m/%d %H:%M:%S")

platform :ios do

  $workspace_name = 'Runner'
  $env_name = 'Runner'
  $scheme_name = $env_name
  $ipa_name = 'flutter-getx-demo'

  lane :build do
  	# 设置小版本号
  	increment_build_number(     
        build_number: "#{sh("git rev-list HEAD | wc -l | tr -d ' '")}"
    )

    # 获取小版本号
  	build_number = get_build_number()

  	# 获取大版本号
  	build_version = get_version_number(configuration: 'Release')

  	build_ios_app(
      workspace: $workspace_name + '.xcworkspace',
      scheme: $scheme_name,
      export_method: 'enterprise',
      output_directory: './build/ipa/',
      output_name: $ipa_name + "-v#{build_version}(#{build_number}).ipa",
      codesigning_identity: 'iPhone Distribution: SCSK Corporation',
      include_bitcode: false,
      clean: true,
      silent: true,
      export_options: {
        compileBitcode: true,
        uploadBitcode: false
      }
    )
  end
end

